// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJtyCPZZT4WOVY5R_IGu_lmd0aOAlqe8',
    appId: '1:586279294560:web:accfd4ef2da4072c665505',
    messagingSenderId: '586279294560',
    projectId: 'liltymobile',
    authDomain: 'liltymobile.firebaseapp.com',
    storageBucket: 'liltymobile.firebasestorage.app',
    measurementId: 'G-1GZSZ1XJM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOy3aol8T8sd3DtLCBtTtwDRz3SLIFN0',
    appId: '1:586279294560:android:777bd79890b3a55e665505',
    messagingSenderId: '586279294560',
    projectId: 'liltymobile',
    storageBucket: 'liltymobile.firebasestorage.app',
  );
}
